name: Lint

on:
  pull_request:
    branches: [ 'main' ]
    paths:
      - 'tests/**'
      - 'requirements.txt'
      - '.github/workflows/lint.yml'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release tag
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c
        with:
          python-version: '3.10'

      - name: Lint
        run: |
          pip install pipenv
          pipenv install -d
          pipenv run make lint